version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
  codeceptjs:
    build:
      context: ./docker/
      args:
        - TZ=${TZ}
        - CODECEPTJS_VERSION=${CODECEPTJS_VERSION:-3.0.7}
    environment:
      HOST_PWD: "${PWD:-.}"
      REPORT_DIR: "${REPORT_DIR:-./reports}"
      NODE_OPTIONS: "--max-old-space-size=6144"
    volumes:
      - "./conf:/tests/conf"
      - "${HOST_PWD:-.}/src:/tests"
      - "${REPORT_DIR:-./reports}:/tests/reports"
    mem_limit: 6g
    memswap_limit: 6g
    working_dir: /tests
    network_mode: "host"
    init: true